server:
  port: 8085
  tomcat:
    # idle-timeout 不可设置 默认是60s
    connection-timeout: 20000 # 请求握手超时时间
    keep-alive-timeout: 60000 # keep-alive请求断开时间

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_shopping_cart?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 10 # 启动时连接数
      maximum-pool-size: 50
      connection-timeout: 30000 # 创建连接等待时间
      max-lifetime: 600000 # 活跃最长时间
      idle-timeout: 60000 # 空闲最长时间

  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: BASIC
      httpclient:
        hc5:
          enabled: true # 开启httpclient5
        max-connections: 200
        max-connections-per-route: 50
        time-to-live: 55 # 连接生存时间

mybatis:
  # mapper映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true