server:
  port: 8086
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    threads:
      max: 1000
      min-spare: 50
    accept-count: 1000 # 队列容量
    # idle-timeout 不可设置 默认是60s
    connection-timeout: 10000 # 等待客户端发起请求的时间
    keep-alive-timeout: 5000 # http空闲时间到后释放
    max-keep-alive-requests: 1000 # 单连接的最大请求数
    max-connections: 500
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_seckill?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
#      minimum-idle: 100 # 启动时连接数 不设置时与maximum-pool-size相同
      maximum-pool-size: 200
      connection-timeout: 30000 # 创建连接等待时间
      max-lifetime: 600000 # 活跃最长时间，比数据库允许最长时间要短
      idle-timeout: 90000 # 空闲最长时间，超过这个时间并且比min值大，会被踢出线程池
      keepalive-time: 60000 # 心跳时间，防止跟数据库断开连接

  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: application/json
        response:
          enabled: true
      client:
        config:
          default:
            logger-level: BASIC
      httpclient:
        hc5:
          enabled: true # 开启httpclient5
        max-connections: 200
        max-connections-per-route: 50
        time-to-live: 180 # 连接生存时间

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    # 生产者确认功能
    publisher-confirm-type: correlated # 异步回调
    publisher-returns: true
    template:
      mandatory: true
    # 消费者
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 3 # next = last * interval
          max-attempts: 4
          stateless: true # 关闭事务: true, 开启事务: false

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
      connect-timeout: 5000ms
      timeout: 5s
#      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-active: 500
          max-idle: 200
          min-idle: 100
          max-wait: 10s
          time-between-eviction-runs: 10s
mybatis:
  # mapper映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

bloom-filter:
  expected-insertions: 1000000
  fpp: 0.01