server:
  port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 50 # 启动时连接数
      maximum-pool-size: 200 # 最大连接数
      connection-timeout: 30000 # 创建连接等待时间
      max-lifetime: 600000 # 活跃最长时间
      idle-timeout: 60000 # 空闲最长时间

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    # 生产者确认功能
    publisher-confirm-type: correlated # 异步回调
    publisher-returns: true
    template:
      mandatory: true
    # 消费者
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 3 # next = last * interval
          max-attempts: 4
          stateless: true # 关闭事务: true, 开启事务: false

  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: BASIC
      httpclient:
        max-connections: 200
        max-connections-per-route: 50

mybatis:
  # mapper映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-tc-server
      username:
      password:
  tx-service-group: seata-cmall-order # 事务组名称
  service:
    vgroup-mapping:
      seata-cmall-order: default
#  data-source-proxy-mode: XA # 默认AT