server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service # 路由标识，唯一
          uri: lb://user-service # 路由目标地址
          predicates: # 路由断言，判断请求符合的规则
            - Path=/api/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/coupon/**
        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/api/goods/**
        - id: seckill-service
          uri: lb://seckill-service
          predicates:
            - Path=/api/seckill/**
        - id: shopping-cart-service
          uri: lb://shopping-cart-service
          predicates:
            - Path=/api/shopping-cart/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://127.0.0.1:8090"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true # 是否允许携带cookies
            maxAge: 360000 # 跨域检验有效期