server:
  port: 10010
  compression:
    enabled: true
    mime-types: application/json
  netty:
    idle-timeout: 60000 # 空闲时间
    connection-timeout: 30000 # 握手超时时间

spring:
  main:
    web-application-type: reactive

  application:
    name: gateway

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
      connect-timeout: 5000ms
      timeout: 5000ms
      client-type: lettuce

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip-type: IPv4

    gateway:
      httpclient:
        pool:
          max-idle-time: 30000
        response-timeout: 15000
      routes:
        - id: user-service # 路由标识，唯一
          uri: lb://user-service # 路由目标地址
          predicates: # 路由断言，判断请求符合的规则
            - Path=/api/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/coupon/**
        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/api/goods/**,/api/homepage/**
        - id: seckill-service
          uri: lb://seckill-service
          predicates:
            - Path=/api/seckill/**
        - id: shopping-cart-service
          uri: lb://shopping-cart-service
          predicates:
            - Path=/api/shopping-cart/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://127.0.0.1:8090"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true # 是否允许携带cookies
            maxAge: 360000 # 跨域检验有效期