server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service # 路由标识，唯一
          uri: lb://userservice # 路由目标地址
          predicates: # 路由断言，判断请求符合的规则
            - Path=/user/**
#          filters:
#            - AddRequestHeader=Truth, I am freaking awesome!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
#      default-filters:
#        - AddRequestHeader=Truth, I am freaking awesome!
#        - AddRequestHeader=origin, gateway
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://127.0.0.1:8090"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true # 是否允许携带cookies
            maxAge: 360000 # 跨域检验有效期