server:
  port: 10010
  compression:
    enabled: true
    mime-types: application/json
  netty:
    idle-timeout: 20000 # 空闲时间
    connection-timeout: 3000 # 握手超时时间
    max-keep-alive-requests: 2000

spring:
  main:
    web-application-type: reactive

  application:
    name: gateway

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
      connect-timeout: 5000ms
      timeout: 5000ms
#      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-active: 500
          max-idle: 200
          min-idle: 100
          max-wait: 10s
          time-between-eviction-runs: 10s

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip-type: IPv4

    gateway:
      httpclient:
        compression: true
        response-timeout: 10s # HTTP 响应超时时间
        connect-timeout: 60000 # HTTP 连接超时时间，毫秒
        pool:
          type: fixed
          max-idle-time: 5000
          max-connections: 500 # 最大连接数限制，支持高并发
          acquire-timeout: 5000 # 获取连接的最大等待时间，毫秒

      routes:
        - id: user-service # 路由标识，唯一
          uri: lb://user-service # 路由目标地址
          predicates: # 路由断言，判断请求符合的规则
            - Path=/api/user/**,/admin/user/**,/admin/mall/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**,/admin/order/**
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/coupon/**,/admin/coupon/**
        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/api/goods/**,/api/homepage/**,/upload/**,/admin/goods/**,/admin/carousel/**,/admin/homepage/**,/admin/category/**,/admin/image/**,
        - id: seckill-service
          uri: lb://seckill-service
          predicates:
            - Path=/api/seckill/**,/admin/seckill/**
          filters:
#            - name: CustomRequestRateLimiter
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@keyResolver}'
                redis-rate-limiter.replenishRate: 100 # 每秒生成领牌数
                redis-rate-limiter.burstCapacity: 2000 # 桶容量
        - id: shopping-cart-service
          uri: lb://shopping-cart-service
          predicates:
            - Path=/api/shopping-cart/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://127.0.0.1:8001" # 好像没用
              - "http://localhost:8001"
              - "http://localhost:8002"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true # 是否允许携带cookies
            maxAge: 360000 # 跨域检验有效期