server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_user?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 1500
      connection-timeout: 30000
      max-lifetime: 60000
      idle-timeout: 600000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    # 生产者确认功能
    publisher-confirm-type: correlated # 异步回调
    publisher-returns: true
    template:
      mandatory: true

  data:
    redis:
      host: redis
      port: 6379
      database: 0
      password: 123456
      connect-timeout: 5000ms
      timeout: 5000ms
      client-type: lettuce

mybatis:
  # mapper映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-tc-server
      username:
      password:
  tx-service-group: seata-cmall-user # 事务组名称
  service:
    vgroup-mapping:
      seata-cmall-user: default
#  data-source-proxy-mode: XA # 默认AT