server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json
  tomcat:
    connection-timeout: 20000 # 请求握手超时时间
    keep-alive-timeout: 600000 # keep-alive请求断开时间

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_coupon?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 10 # 启动时连接数 不设置时与maximum-pool-size相同
      maximum-pool-size: 50
      connection-timeout: 30000 # 创建连接等待时间
      max-lifetime: 600000 # 活跃最长时间，比数据库允许最长时间要短
      idle-timeout: 90000 # 空闲最长时间，超过这个时间并且比min值大，会被踢出线程池
      keepalive-time: 60000 # 心跳时间，防止跟数据库断开连接

  cloud:
    openfeign:
      compression:
        request:
          enabled: true
          mime-types: application/json
        response:
          enabled: true
      client:
        config:
          default:
            logger-level: BASIC
      httpclient:
        hc5:
          enabled: true # 开启httpclient5
        max-connections: 200
        max-connections-per-route: 50
        time-to-live: 180 # 连接生存时间

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    # 消费者
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 3 # next = last * interval
          max-attempts: 4
          stateless: true # 关闭事务: true, 开启事务: false

mybatis:
  # mapper映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true